routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\RegisterController;
  
Route::get('admission', [RegistrationController::class, 'index']);
Route::post('admission', [RegistrationController::class, 'store']);

Route::get('storage', function () {
    return \Artisan::call('storage:link');
});

Route::group(['namespace' => 'App\Http\Controllers'], function ()
 {
    Route::group(['prefix'=>'admin-control', 'as'=>'admin.'] , function(){

        Route::get('/login','LoginController@index')->name('login');
        Route::post('/login','LoginController@login')->name('login');

      Route::group(['middleware' => 'admin'], function(){
          Route::get('/logout','LoginController@logout')->name('logout');
          Route::get('/','DashboardController@dashboard')->name('dashboard');
          Route::get('editprofile','EditprofileController@index')->name('editprofile');
          Route::get('changepassword','ChangepasswordController@index')->name('changepassword');
          Route::get('sitesetting','SiteController@index')->name('sitesetting');
          
          Route::post('sitesetting','SiteController@store')->name('site.store');
          Route::get('menu_item/delete', 'MenuItemController@destroy')->name('menu_item.destroy');

          // Route::delete('media/delete/{media}', 'MediaController@destroy')->name('media.destroy');
          // Route::get('media/update', 'MediaController@destroy')->name('media.update');
      
          // Route::get('menu', 'SelectmenuController@create')->name('menu.create');
          // Route::get('menu', 'SelectmenuController@index')->name('menu.index');
          // Route::get('menuit', 'MenuController@create')->name('menuit.create');
          // Route::get('menuit', 'MenuController@index')->name('menuit.index');

          Route::resources([
            'menu'      => 'MenuController',
            'menu-item' => 'MenuItemController',
            'media'     =>  'MediaController',
          ]);

          Route::post('menu-item/sort', 'MenuItemController@updateSort')->name('menu-item.update.sort');
        
          Route::get('category/{post_type:slug}', 'CategoryController@index')->name('category.index');
          Route::get('category/{post_type:slug}/create', 'CategoryController@create')->name('category.create');
          Route::get('category/{post_type:slug}/edit/{category:slug}', 'CategoryController@edit')->name('category.edit');
          Route::put('category/{post_type:slug}/update/{category:slug}', 'CategoryController@update')->name('category.update');
          Route::delete('category/{post_type:slug}/delete/{category:slug}', 'CategoryController@destroy')->name('category.destroy');
          Route::post('category/{post_type:slug}/store', 'CategoryController@store')->name('category.store');


          Route::get('{post_type:slug}', 'PostController@index')->name('post.index');
          Route::get('{post_type:slug}/create', 'PostController@create')->name('post.create');
          Route::get('{post_type:slug}/edit/{post:slug}', 'PostController@edit')->name('post.edit');
          Route::put('{post_type:slug}/update/{post:slug}', 'PostController@update')->name('post.update');
          Route::delete('{post_type:slug}/delete/{post:slug}', 'PostController@destroy')->name('post.destroy');
          Route::post('{post_type:slug}/store', 'PostController@store')->name('post.store');
      });
  });

  # Web Routes
  Route::group(['namespace' => 'Web'], function () {
    Route::get('/', 'HomeController@index')->name('Home');
    Route::post('/contact', 'ContactUsController@sendEnquiry')->name('contact.send');
    Route::post('/admission', 'RegistrationController@sendEnquiry')->name('admission.send');
    
    Route::get('/{post:slug}', 'PostController@show')->name('post.show');
  });

  
    
});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;

    protected $casts = [
        'location' => 'array',
    ];

    public function menu_items()
    {
        return $this->hasMany(MenuItem::class)->orderBy('sortby');
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Models\Menu;
use App\Models\PostType;
use App\Models\MenuLocation;
use Illuminate\Http\Request;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menus = Menu::where('site_id', $this->_site->id)->latest()->paginate(10);
        return view('backend.pages.menu.index', compact('menus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $request->flush();
        // $all_post_types = PostType::where('site_id',$this->_site->id)->pluck('name','slug');
        $menu_locations = MenuLocation::pluck('name', 'keyword');
        return view('backend.pages.menu.create', compact('menu_locations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $menu = new Menu();
        $menu->name = $request->name;
        $menu->location = $request->menu_location;
        $menu->site_id = $this->_site->id;
        $menu->save();

        return redirect( route('admin.menu.index') );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function show(Menu $menu)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function edit(Menu $menu)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Menu $menu)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function destroy(Menu $menu)
    {
        //
    }
}

resources/views/backend/pages/menu/create.blade.php
@extends('backend.layouts.inner')
@section('site_title','Add items')
@section('content')


   <div class="container">
       <div class="content">
            <div class="row">
                <div class="col-5">
                    {{ Form::open(['url' => route('admin.menu.store')]) }}
                    <div class="mb-3">
                        {{ Form::label('name') }}
                        {{ Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Menu Name']); }}
                    </div>
                    
                    @foreach($menu_locations as $keyword => $name)

                    <div class="custom-control custom-checkbox mb-3">
                        {{ Form::checkbox('menu_location[]', $keyword, 0, ['class' => 'custom-control-input', 'id' => 'menu_location_' . $keyword]) }}
                        {{ Form::label('menu_location_' . $keyword, $name, ['class' => 'custom-control-label']) }}
                    </div>

                    @endforeach
    
                     <input class="btn btn-primary" type="submit" value="Submit">    
                     
                     {{ Form::close() }}
                </div>
            </div>

        </div>
        
    </div>

</div>

@endsection

resources/views/backend/pages/menu/index.blade.php
@extends('backend.layouts.inner')
@section('site_title','View menu items')
@section('content')
           <div class="card">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    DataTable Example
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            
                                <tr>
                                    <th>S. No.</th>
                                    <th>Name</th>
                                    <th>Location</th>
                                </tr>
                                <tbody>
                                    @foreach($menus as $i => $m)
                                    <tr>
                                        <td>{{ $i + $menus->firstItem() }}</td>
                                        <td>{{ $m->name }}</td>
                                        <td>{{ $m->location }}</td>
                                    </tr>
                                    @endforeach
                           </tbody>
                        </table> 
                    </div>  
                </div>  
            </div>
@endsection