routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\RegisterController;
  
Route::get('admission', [RegistrationController::class, 'index']);
Route::post('admission', [RegistrationController::class, 'store']);

Route::get('storage', function () {
    return \Artisan::call('storage:link');
});

Route::group(['namespace' => 'App\Http\Controllers'], function ()
 {
    Route::group(['prefix'=>'admin-control', 'as'=>'admin.'] , function(){

        Route::get('/login','LoginController@index')->name('login');
        Route::post('/login','LoginController@login')->name('login');

      Route::group(['middleware' => 'admin'], function(){
          Route::get('/logout','LoginController@logout')->name('logout');
          Route::get('/','DashboardController@dashboard')->name('dashboard');
          Route::get('editprofile','EditprofileController@index')->name('editprofile');
          Route::get('changepassword','ChangepasswordController@index')->name('changepassword');
          Route::get('sitesetting','SiteController@index')->name('sitesetting');
          
          Route::post('sitesetting','SiteController@store')->name('site.store');
          Route::get('menu_item/delete', 'MenuItemController@destroy')->name('menu_item.destroy');

          // Route::delete('media/delete/{media}', 'MediaController@destroy')->name('media.destroy');
          // Route::get('media/update', 'MediaController@destroy')->name('media.update');
      
          // Route::get('menu', 'SelectmenuController@create')->name('menu.create');
          // Route::get('menu', 'SelectmenuController@index')->name('menu.index');
          // Route::get('menuit', 'MenuController@create')->name('menuit.create');
          // Route::get('menuit', 'MenuController@index')->name('menuit.index');

          Route::resources([
            'menu'      => 'MenuController',
            'menu-item' => 'MenuItemController',
            'media'     =>  'MediaController',
          ]);

          Route::post('menu-item/sort', 'MenuItemController@updateSort')->name('menu-item.update.sort');
        
          Route::get('category/{post_type:slug}', 'CategoryController@index')->name('category.index');
          Route::get('category/{post_type:slug}/create', 'CategoryController@create')->name('category.create');
          Route::get('category/{post_type:slug}/edit/{category:slug}', 'CategoryController@edit')->name('category.edit');
          Route::put('category/{post_type:slug}/update/{category:slug}', 'CategoryController@update')->name('category.update');
          Route::delete('category/{post_type:slug}/delete/{category:slug}', 'CategoryController@destroy')->name('category.destroy');
          Route::post('category/{post_type:slug}/store', 'CategoryController@store')->name('category.store');


          Route::get('{post_type:slug}', 'PostController@index')->name('post.index');
          Route::get('{post_type:slug}/create', 'PostController@create')->name('post.create');
          Route::get('{post_type:slug}/edit/{post:slug}', 'PostController@edit')->name('post.edit');
          Route::put('{post_type:slug}/update/{post:slug}', 'PostController@update')->name('post.update');
          Route::delete('{post_type:slug}/delete/{post:slug}', 'PostController@destroy')->name('post.destroy');
          Route::post('{post_type:slug}/store', 'PostController@store')->name('post.store');
      });
  });

  # Web Routes
  Route::group(['namespace' => 'Web'], function () {
    Route::get('/', 'HomeController@index')->name('Home');
    Route::post('/contact', 'ContactUsController@sendEnquiry')->name('contact.send');
    Route::post('/admission', 'RegistrationController@sendEnquiry')->name('admission.send');
    
    Route::get('/{post:slug}', 'PostController@show')->name('post.show');
  });

  
    
});

app/Models/MenuItem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MenuItem extends Model
{
    use HasFactory;
    protected $with = ['menu_item', 'post', 'category'];

    public function menu()
    {
        return $this->belongsTo(Menu::class);
    }
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function post()
    {
        return $this->belongsTo(Post::class);
    }
    public function menu_item()
    {
        return $this->hasMany(MenuItem::class)->orderBy('sortby');
    }
}

app/Http/Controllers/Api/MenuItemController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\MenuItem;
use Illuminate\Http\Request;

class MenuItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $menu_items = MenuItem::where('menu_id', $request->menu_id)->pluck('label', 'id');

        return response()->json($menu_items);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\MenuItem  $menuItem
     * @return \Illuminate\Http\Response
     */
    public function show(MenuItem $menuItem)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\MenuItem  $menuItem
     * @return \Illuminate\Http\Response
     */
    public function edit(MenuItem $menuItem)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\MenuItem  $menuItem
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, MenuItem $menuItem)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\MenuItem  $menuItem
     * @return \Illuminate\Http\Response
     */
    public function destroy(MenuItem $menuItem)
    {
        //
    }
}

app/Http/Controllers/MenuItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\MenuItem;
use App\Models\Post;
use App\Models\PostType;
use App\Models\Menu;
use Illuminate\Http\Request

class MenuItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all_post_types = PostType::where('site_id',$this->_site->id)->pluck('name','slug');
        $menus = Menu::with(['menu_items' => function ($q) {
            $q->whereNull('menu_item_id')->orderBy('sortby');
        }])->where('site_id', $this->_site->id)->get();

        // dd($menus);
        return view ('backend.pages.menu_item.index', compact('all_post_types', 'menus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $request->flush();

        $all_post_types = PostType::where('site_id',$this->_site->id)->pluck('name', 'slug');
        $menus = Menu::where('site_id',$this->_site->id)->pluck('name', 'id');
        $parent = [];
        $posts = [];
        return view ('backend.pages.menu_item.create', compact('all_post_types', 'menus', 'parent', 'posts'));
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $menuItem = new MenuItem();
        $menuItem->menu_id = $request->menu_id;
        $menuItem->menu_item_id = $request->menu_item_id;
        $menuItem->post_type = $request->post_type;
        $menuItem->label = $request->label;
        $menuItem->type = $request->type;
        $menuItem->link = $request->link;
        $menuItem->target = $request->target;
        $menuItem->post_id = $request->post_id;
        $menuItem->category_id = $request->category_id;
        $menuItem->save();

        return redirect( route('admin.menu-item.index') );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\MenuItem  $menuItem
     * @return \Illuminate\Http\Response
     */
    public function show(MenuItem $menuItem)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\MenuItem  $menuItem
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, MenuItem $menuItem)
    {
        $request->replace($menuItem->toArray());
        $request->flash();

        $all_post_types = PostType::where('site_id',$this->_site->id)->pluck('name', 'slug');
        $menus = Menu::where('site_id',$this->_site->id)->pluck('name', 'id');
        $parent = [];
        if(!empty($menuItem->menu_id))
        {
            $parent = MenuItem::where('menu_id', $menuItem->menu_id)->pluck('label', 'id');
        }
        $posts = [];
        if(!empty($menuItem->post_type))
        {
            $posts = Post::where('post_type', $menuItem->post_type)->where('site_id', $this->_site->id)->pluck('title', 'id');
        }
        return view ('backend.pages.menu_item.edit', compact('all_post_types', 'menus', 'parent', 'menuItem', 'posts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\MenuItem  $menuItem
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, MenuItem $menuItem)
    {
        $menuItem->menu_id = $request->menu_id;
        $menuItem->menu_item_id = $request->menu_item_id;
        $menuItem->post_type = $request->post_type;
        $menuItem->label = $request->label;
        $menuItem->type = $request->type;
        $menuItem->link = $request->link;
        $menuItem->target = $request->target;
        $menuItem->post_id = $request->post_id;
        $menuItem->category_id = $request->category_id;
        $menuItem->save();

        return redirect( route('admin.menu-item.index') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\MenuItem  $menuItem
     * @return \Illuminate\Http\Response
     */
    public function destroy(MenuItem $menuItem)
    {
        $menuItem->delete();
        return redirect( route('admin.menu-item.index') );
    }

    public function updateSort(Request $request)
    {
        foreach ($request->ids as $index => $id) {
            $menuItem = MenuItem::find($id);
            $menuItem->sortby = $index;
            $menuItem->save();
        }

        return response()->json(['msg' => 'order updated']);
    }
}

resources/views/backend/pages/menu_item/create.blade.php
@extends('backend.layouts.inner')
@section('site_title','Add menu items')
@section('content')


<div class="container-fluid">
    {{ Form::open(['url' => route('admin.menu-item.store')]) }}
    <div>
        @include('backend.pages.menu_item.form')
        <div class="mb-3">
            <button class="btn ol btn-outline-primary btn-block">ADD TO MENU</button>
        </div>
    </div>
    {{ Form::close() }}

</div>


@endsection

resources/views/backend/pages/menu_item/edit.blade.php
@extends('backend.layouts.inner')
@section('site_title','Edit menu items')
@section('content')


<div class="container-fluid">
    {{ Form::open(['url' => route('admin.menu-item.update', [$menuItem->id]), 'method' => 'PUT']) }}
        <div>
            @include('backend.pages.menu_item.form')
            <div class="mb-3">
                <button class="btn ol btn-outline-primary btn-block">Update</button>
            </div>
        </div>
    {{ Form::close() }}

</div> 
    

@endsection

resources/views/backend/pages/menu_item/form.blade.php
<div>
    <div class="form-check form-check-inline">
        {{ Form::radio('type', 'post', 1, ['class' => 'form-check-input menu_type', 'id' => 'type_post']) }}
        {{ Form::label('type_post', 'Post', ['class' => 'form-check-label']) }}
    </div>
    <div class="form-check form-check-inline">
        {{ Form::radio('type', 'category', null, ['class' => 'form-check-input menu_type', 'id' => 'type_category']) }}
        {{ Form::label('type_category', 'Category', ['class' => 'form-check-label']) }}
    </div>
    <div class="form-check form-check-inline">
        {{ Form::radio('type', 'external', null, ['class' => 'form-check-input menu_type', 'id' => 'type_external']) }}
        {{ Form::label('type_external', 'Other', ['class' => 'form-check-label']) }}
    </div>
</div>
<div class="mb-3">
    {{ Form::label('menu_id') }}
    {{ Form::select('menu_id', $menus, null, ['class' => 'form-control menu', 'placeholder' => 'Select Menu', 'data-url' => route('ajax.menu-item.index'), 'data-target' => '#menu_item_id','required' => 'required']) }}
</div>
        
<div class="mb-3">
    {{ Form::label('menu_item_id', 'Parent Menu Item') }}
    {{ Form::select('menu_item_id', $parent, null, ['class' => 'form-control', 'placeholder' => 'Select Parent Menu Item']) }}
</div>  
<div class="mb-3 category post">
    {{ Form::label('post_type') }}
    {{ Form::select('post_type', $all_post_types, null, ['class' => 'form-control post_type', 'placeholder' => 'Select Post Type', 'data-url' => route('ajax.post_category')]) }}
</div>
<div class="mb-3 category" style="display: none">
    {{ Form::label('category_id', 'Category') }}
    {{ Form::select('category_id', [], null, ['class' => 'form-control', 'placeholder' => 'Select Category']) }}
</div>
<div class="mb-3 post">
    {{ Form::label('post_id', 'Post') }}
    {{ Form::select('post_id', $posts, null, ['class' => 'form-control', 'placeholder' => 'Select Post']) }}
</div>
<div class="mb-3">
    {{ Form::label('label') }}
    {{ Form::text('label', null, ['class' => 'form-control', 'placeholder' => 'Enter Label']) }}
</div>
<div class="mb-3 external" style="display: none">
    {{ Form::label('link') }}
    {{ Form::text('link', null, ['class' => 'form-control', 'placeholder' => 'Enter Link']) }}
</div>
<div class="mb-3">
    {{ Form::label('target') }}
    {{ Form::select('target', ['_self' => 'Current Tab', '_blank' => 'New Tab'], null, ['class' => 'form-control']) }}
</div>
<div class="mb-3">
    {{ Form::label('follow') }}
    {{ Form::select('follow', ['dofollow' => 'Do Follow', 'nofollow' => 'No Follow'], null, ['class' => 'form-control']) }}
</div>

resources/views/backend/pages/menu_item/index.blade.php
@extends('backend.layouts.inner')
@section('site_title','View menu items')
@section('content')
<div class="card">
   <div class="card-header">
      <i class="fas fa-table mr-1"></i>
      DataTable Example
   </div>
   <div class="card-body">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
         @foreach($menus as $i => $m)
         <li class="nav-item">
            <a class="nav-link{{$i == 0 ? ' active' : ''}}" id="home-tab-{{ $m->id }}" data-toggle="tab" href="#home-{{ $m->id }}" role="tab" aria-controls="home" aria-selected="true">{{ $m->name }}</a>
         </li>
         @endforeach
      </ul>
      <div class="tab-content" id="myTabContent">
         @foreach($menus as $i => $m)
         <div class="tab-pane fade{{ $i == 0 ? ' show active' : ''}}" id="home-{{ $m->id }}" role="tabpanel" aria-labelledby="home-tab">
            <div class="menu-items mt-3">
               <ul class="ul-sortable">
                     @foreach($m->menu_items as $mitem)
                     <li class="item-{{ $mitem->id }}" data-id="{{ $mitem->id }}">
                        <div class="menu-item-list">
                            <strong>{{ $mitem->label }}</strong>
                            <div class="d-flex align-items-center">
                                {{ $mitem->type }}
                                <div class="dropdown">
                                    <button class="btn btn-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-ellipsis-v"></i>
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{{ route('admin.menu-item.edit', [$mitem->id]) }}">Edit</a>
                                        {{ Form::open(['url' => route('admin.menu-item.destroy', [$mitem->id]), 'method' => 'delete']) }}
                                        <button class="dropdown-item">Delete</button>
                                        {{ Form::close() }}
                                    </div>
                                </div>  
                            </div>
                        </div>
                        @if(!$mitem->menu_item->isEmpty())
                        @include('backend.pages.menu_item.recursive', ['mitems' => $mitem->menu_item])
                        @endif
                     </li>
                     @endforeach
               </ul>
            </div>
         </div>
         @endforeach
      </div>
   </div>
</div>
@endsection

@section('extra_scripts')
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script>
    $( function() {
        $( ".ul-sortable" ).sortable({
            axis: "y",
            update: function (event, ui) {
                // console.log('sort: ', $(this).sortable('serialize'));
                var li_ids = [];
                $.each($(this).find('li'), function (i, row) {
                    li_ids.push($(row).data('id'));
                });
                // console.log('sort: ', data);
                $.ajax({
                    url: "{{ route('admin.menu-item.update.sort') }}",
                    method: 'POST',
                    data: {
                        ids: li_ids,
                        _token: "{{ csrf_token() }}"
                    },
                    success: function(res) {
                        console.log('order updated.');
                    }
                });
            }
        });
    });
    </script>
@endsection

resources/views/backend/pages/menu_item/recursive.blade.php
<ul class="ul-sortable">
    @foreach($mitems as $mitem2)
        <li id="item-{{ $mitem2->id }}" data-id="{{ $mitem2->id }}">
            <div class="menu-item-list">
            <strong>{{ $mitem2->label }}</strong><br>
            <div class="d-flex align-items-center">
            {{ $mitem2->type }}
             <!-- <a href=""> <i class="fas fa-ellipsis-v"></i> </a> -->
                <div class="dropdown">
                    <button class="btn btn-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v"></i>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{{ route('admin.menu-item.edit', [$mitem2->id]) }}">Edit</a>
                        {{ Form::open(['url' => route('admin.menu-item.destroy', [$mitem2->id]), 'method' => 'delete']) }}
                        <button class="dropdown-item">Delete</button>
                        {{ Form::close() }}
                    </div>
                </div>
             </div>
             </div>
            @if(!$mitem2->menu_item->isEmpty())
                @include('backend.pages.menu_item.recursive', ['mitems' => $mitem2->menu_item])
            @endif
        </li>
    @endforeach
</ul>