routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\RegisterController;
  
Route::get('admission', [RegistrationController::class, 'index']);
Route::post('admission', [RegistrationController::class, 'store']);

Route::get('storage', function () {
    return \Artisan::call('storage:link');
});

Route::group(['namespace' => 'App\Http\Controllers'], function ()
 {
    Route::group(['prefix'=>'admin-control', 'as'=>'admin.'] , function(){

        Route::get('/login','LoginController@index')->name('login');
        Route::post('/login','LoginController@login')->name('login');

      Route::group(['middleware' => 'admin'], function(){
          Route::get('/logout','LoginController@logout')->name('logout');
          Route::get('/','DashboardController@dashboard')->name('dashboard');
          Route::get('editprofile','EditprofileController@index')->name('editprofile');
          Route::get('changepassword','ChangepasswordController@index')->name('changepassword');
          Route::get('sitesetting','SiteController@index')->name('sitesetting');
          
          Route::post('sitesetting','SiteController@store')->name('site.store');
          Route::get('menu_item/delete', 'MenuItemController@destroy')->name('menu_item.destroy');

          // Route::delete('media/delete/{media}', 'MediaController@destroy')->name('media.destroy');
          // Route::get('media/update', 'MediaController@destroy')->name('media.update');
      
          // Route::get('menu', 'SelectmenuController@create')->name('menu.create');
          // Route::get('menu', 'SelectmenuController@index')->name('menu.index');
          // Route::get('menuit', 'MenuController@create')->name('menuit.create');
          // Route::get('menuit', 'MenuController@index')->name('menuit.index');

          Route::resources([
            'menu'      => 'MenuController',
            'menu-item' => 'MenuItemController',
            'media'     =>  'MediaController',
          ]);

          Route::post('menu-item/sort', 'MenuItemController@updateSort')->name('menu-item.update.sort');
        
          Route::get('category/{post_type:slug}', 'CategoryController@index')->name('category.index');
          Route::get('category/{post_type:slug}/create', 'CategoryController@create')->name('category.create');
          Route::get('category/{post_type:slug}/edit/{category:slug}', 'CategoryController@edit')->name('category.edit');
          Route::put('category/{post_type:slug}/update/{category:slug}', 'CategoryController@update')->name('category.update');
          Route::delete('category/{post_type:slug}/delete/{category:slug}', 'CategoryController@destroy')->name('category.destroy');
          Route::post('category/{post_type:slug}/store', 'CategoryController@store')->name('category.store');


          Route::get('{post_type:slug}', 'PostController@index')->name('post.index');
          Route::get('{post_type:slug}/create', 'PostController@create')->name('post.create');
          Route::get('{post_type:slug}/edit/{post:slug}', 'PostController@edit')->name('post.edit');
          Route::put('{post_type:slug}/update/{post:slug}', 'PostController@update')->name('post.update');
          Route::delete('{post_type:slug}/delete/{post:slug}', 'PostController@destroy')->name('post.destroy');
          Route::post('{post_type:slug}/store', 'PostController@store')->name('post.store');
      });
  });

  # Web Routes
  Route::group(['namespace' => 'Web'], function () {
    Route::get('/', 'HomeController@index')->name('Home');
    Route::post('/contact', 'ContactUsController@sendEnquiry')->name('contact.send');
    Route::post('/admission', 'RegistrationController@sendEnquiry')->name('admission.send');
    
    Route::get('/{post:slug}', 'PostController@show')->name('post.show');
  });

  
    
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    public function categories()
    {
        return $this->belongsToMany(Category::class, 'post_categories');
    }

    public function post_meta()
    {
        return $this->hasMany(PostMeta::class);
    }

    public function getMetaValue($meta_name)
    {
        $field = PostMeta::where('post_id', $this->id)->where('meta_name', $meta_name)->first();
        return !empty($field->meta_value) ? $field->meta_value : "";
    }
}

app/Models/PostType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PostType extends Model
{
    use HasFactory;

    public function fields()
    {
        return PostField::where('post_type', $this->slug)->first();
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\PostType;
use App\Models\PostMeta;
use App\Models\Category;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PostType $post_type)

    {
        $posts = Post::where('post_type', $post_type->slug)->latest()->paginate(10);
        return view('backend.pages.post.index', compact('post_type', 'posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, PostType $post_type)
    {
        $post_fields = $post_type->fields();

        // dd($post_fields->extra_fields);
        $request->flush();
        $parent_categories = Category::with('categories')->where('site_id', $this->_site->id)->whereNull('category_id')->select('title', 'id', 'category_id')->get();
        return view('backend.pages.post.create', compact('post_type', 'post_fields', 'parent_categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $post_type)
    {
        
        $post = new Post();
        $post->title = $request->title;
        $post->slug = $request->slug;
        $post->excerpt = $request->excerpt;
        $post->description = $request->description;
        $post->post_type = $post_type;
        $post->site_id = $this->_site->id;
        $post->meta_keywords=$request->meta_keywords;
        $post->meta_title = $request->meta_title;
        $post->meta_description = $request->meta_description;
        $post->template = $request->template;
        
        if ($request->hasfile('image')){
            $post->image = $request->file('image')->store($this->_site->domain . '/imgs/post/', 'public');
        }

        $post->save();

        if(!empty($request->extra_fields)) :
            $post->post_meta()->delete();
            foreach ($request->extra_fields as $meta_name => $meta_value) {
                $post_meta = new PostMeta();
                $post_meta->meta_name = $meta_name;
                $post_meta->meta_value = $meta_value;
                $post_meta->post_id = $post->id;
                $post_meta->save();
            }
        endif;

        if(!empty($request->category)) {
            $post->categories()->sync($request->category);
        }

        return redirect( route('admin.post.index', [$post_type]) );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post  $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit( Request $request, $post_type_slug, Post $post)
    {
        $post_type = PostType::where('slug', $post_type_slug)->firstOrFail();
        $post_fields = $post_type->fields();
        $post_arr = $post->toArray();
        $post_arr['category'] = $post->categories()->pluck('categories.id')->toArray();
        $request->replace($post_arr);
        $request->flash();

        $parent_categories = Category::with('categories')->where('site_id', $this->_site->id)->whereNull('category_id')->select('title', 'id', 'category_id')->get();

        return view('backend.pages.post.edit', compact('post', 'post_type', 'post_fields', 'parent_categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $post_type ,$post)
    {
        $post = Post::findOrFail($post);
        $post->post_type=$post_type;
        $post->title = $request->title;
        $post->slug = $request->slug;
        $post->excerpt = $request->excerpt;
        $post->description = $request->description;
        $post->meta_keywords=$request->meta_keywords;
        $post->meta_title = $request->meta_title;
        $post->meta_description = $request->meta_description;
        $post->template = $request->template;
        
        if ($request->hasfile('image')){
            $post->image = $request->file('image')->store($this->_site->domain . '/imgs/post/', 'public');
        }

        $post->save();
        
        $post->categories()->sync( $request->category );

        return redirect( route('admin.post.index', [$post_type]) );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy( $post_type, $slug )
    {   
        $post = Post::where('slug',$slug)->where('post_type',$post_type)->firstOrFail();
        $post->delete();
        return redirect( route('admin.post.index',$post_type) );
    }
}

app/Http/Controllers/Web/PostController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Post $post)
    {
        $data = compact('post');
        // dd($post->post_type);
        switch ($post->template) {
            case 'photo-gallery':
                $data['galleries'] = Post::where('post_type', 'Photo-gallary')->paginate(12);
                break;
            
            case 'download':
                $data['downloads'] = Post::where('post_type', 'Download')->paginate(12);
                break;
            
            case 'facility':
                $data['facilities'] = Post::where('post_type', 'facility')->paginate(12);
                break;
            
            case 'tc':
                $data['tcs'] = [];

                if(!empty($request->tc_num) || !empty($request->enroll)) {
                    $posts = Post::query();
                    if(!empty($request->tc_num)) {
                        $posts->whereHas('post_meta', function ($q) use ($request) {
                            $q->where('meta_name', 'tc_number')->where('meta_value', 'LIKE', $request->tc_num.'%');
                        });
                    } else if (!empty($request->enroll)) {
                        $posts->whereHas('post_meta', function ($q) use ($request) {
                            $q->where('meta_name', 'enroll_no')->where('meta_value', 'LIKE', $request->enroll.'%');
                        });
                    }
                    $data['tcs'] = $posts->orderBy('title')->paginate(12);
                }
                break;

            default:
                # code...
                break;
        }
        // dd($data);
        return view('web.inc.' . $post->template, $data);    
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

resources/views/backend/pages/post/create.blade.php
@extends('backend.layouts.inner')
@section('site_title','Add page')
@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Add {{$post_type->name}}</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard')}}">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.post.index', $post_type->slug)}}">{{ $post_type->name }}</a>
                </li>
                <li class="breadcrumb-item active">Add {{$post_type->name}}</li>
            </ol>
        </div>
        <div class="card-body">
            {{ Form::open(['url' => route('admin.post.store' ,$post_type->slug),  'files' => true, 'method' => 'post']) }}
            @include('backend.pages.post.form')
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
            {{ Form::close() }}
        </div>
    </div>

</div>
@endsection

resources/views/backend/pages/post/edit.blade.php
@extends('backend.layouts.inner')
@section('site_title','Add post')
@section('content')


<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard')}}">Database Table</a>
                </li>
                <li class="breadcrumb-item active">Add Post</li>
            </ol>
        </div>
        <div class="card-body">

            {{ Form::open(['url' => route('admin.post.update', [$post_type->slug, $post->id]), 'files' => true, 'method' => 'PUT'] )}}
            @include('backend.pages.post.form')

            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>

@endsection

resources/views/backend/pages/post/form.blade.php
<div class="row">
    <div class="col-lg-8">
        @if(!$post_fields || !empty($post_fields->title))
        @php
        $label = !empty($post_fields->title) ? $post_fields->title : 'Title';
        @endphp
        <div class="mb-3">
            {{ Form::label('title', $label) }}
            {{ Form::text('title', null, ['class' => 'form-control title', 'placeholder' => 'Enter ' . $label, 'data-target' => '#slug']) }}
        </div>
        @endif
        <div class="mb-3">
            {{ Form::label('slug') }}
            {{ Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Enter Slug']) }}
        </div>
        @if(!$post_fields || !empty($post_fields->excerpt))
        @php
        $label = !empty($post_fields->excerpt) ? $post_fields->excerpt : 'Short Description';
        @endphp
        <div class="mb-3">
            {{ Form::label('excerpt', $label) }}
            {{ Form::textarea('excerpt', null, ['class' => 'form-control', 'placeholder' => 'Enter ' . $label]) }}
        </div>
        @endif

        @if(!$post_fields || !empty($post_fields->description))
        @php
        $label = !empty($post_fields->description) ? $post_fields->description : 'Description';
        @endphp
        <div class="mb-3">
            {{ Form::label('description', $label) }}
            {{ Form::textarea('description', null, ['class' => 'form-control myEditor', 'placeholder' => 'Enter ' . $label]) }}
        </div>
        @endif


        @if(!empty($post_fields->extra_fields))
        @foreach ($post_fields->extra_fields as $pf)
        <div class="mb-3">
            {{ Form::label('extra_fields['.$pf['meta_name'].']', $pf['label']) }}

            @if($pf['type'] === 'file')
            {{ Form::hidden('extra_fields['.$pf['meta_name'].']', null, ['id' => 'file_' . $pf['meta_name']]) }}
            <!-- Button trigger modal -->
            <div>
                <button type="button" class="btn btn-primary filepicker" data-target="#file_{{ $pf['meta_name'] }}">
                    Choose File
                </button>
            </div>
            @else
            {{ Form::text('extra_fields['.$pf['meta_name'].']', null, ['class' => 'form-control', 'placeholder' => 'Enter ' . $pf['label']]) }}
            @endif
        </div>
        @endforeach
        @endif
    </div>

    <div class="col-lg-4">

        @if(!$post_fields || !empty($post_fields->image))

        @php
        $label = !empty($post_fields->image) ? $post_fields->image : 'Featured Image';
        @endphp
        <div class="mb-3">
            {{ Form::label('image', $label) }}
            @if(!empty($post->image))
            <label for="image" class="card mb-3" style="width:10rem;">
                <img src="{{url('storage/'.$post->image)}}" alt=".." class="card-img-top" name="image">
            </label>
            @endif
            <label class="btn btn-block btn-primary">
                {{Form::file('image',['style'=>'display:none;']) }}
                Choose Image
            </label>
        </div>
        @endif

        @if($post_type->is_category == 'Y')

        <div class="main_category">
            <h1 class="myhedding">CATEGORY</h1>
            <ul>
                @foreach($parent_categories as $pc)
                <li>
                    <!-- <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                MEN'S WEAR<b class="caret"></b>
                </a> -->
                    <label>
                        {{ Form::checkbox('category[]', $pc->id) }}
                        {{ $pc->title }}
                    </label>
                    <ul>
                        @foreach($pc->categories as $subc)
                        <li><label class="checkbox">
                                {{ Form::checkbox('category[]', $subc->id) }}
                                {{ $subc->title }}
                            </label>
                        </li>
                        @endforeach
                    </ul>
                </li>
                @endforeach
            </ul>
        </div>
        @endif

        @if(!$post_fields || !empty($post_fields->meta_title))

        @php
        $label = !empty($post_fields->title) ? $post_fields->title : 'Title';
        @endphp
        <div class="mb-3">
            {{ Form::label('meta_title', $label) }}
            {{ Form::text('meta_title', null, ['class' => 'form-control', 'placeholder' => 'Enter ' . $label]) }}
        </div>
        @endif

        @if(!$post_fields || !empty($post_fields->meta_keywords))
        @php
        $label = !empty($post_fields->meta_keywords) ? $post_fields->meta_keywords : 'Meta Keywords';
        @endphp
        <div class="mb-3">
            {{ Form::label('meta_keywords', $label) }}
            {{ Form::text('meta_keywords', null, ['class' => 'form-control', 'placeholder' => 'Enter ' . $label]) }}
        </div>
        @endif

        @if(!$post_fields || !empty($post_fields->meta_description))
        @php
        $label = !empty($post_fields->meta_description) ? $post_fields->meta_description : 'Meta Description';
        @endphp
        <div class="mb-3">
            {{ Form::label('meta_description', $label) }}
            {{ Form::textarea('meta_description', null, ['class' => 'form-control', 'placeholder' => 'Enter ' . $label]) }}
        </div>
        @endif

        @if(!$post_fields || !empty($post_fields->template))
        @php
        $label = !empty($post_fields->template) ? $post_fields->template : 'Template';
        @endphp
        <div class="mb-3">
            {{ Form::label('template', $label) }}
            {{ Form::select('template', ['page' => 'Page', 'photo-gallery' => 'Photo Gallery', 'home' => 'Home', 'contact' => 'Contact', 'download' => 'Download', 'facility' => 'Facility', 'admission' => 'Online Admission', 'tc' => 'TC'], 'page', ['class' => 'form-control', 'placeholder' => 'Select ' . $label]) }}

            
        </div>
        @endif

    </div>

resources/views/backend/pages/post/index.blade.php
@extends('backend.layouts.inner')
@section('site_title','View Page')
@section('content')
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Tables</h1>

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                                <ol class="breadcrumb mb-4">
                                    <li class="breadcrumb-item">
                                        <a href="{{ route('admin.dashboard')}}">Dasgboard</a>
                                    </li>
                                    <li class="breadcrumb-item active">View {{$post_type->name}}</li>
                                </ol>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                    <tr>
                                        <th>S.NO</th>
                                        <th>Title</th>
                                        <th>Short-Discription</th>
                                        <th>Image</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                  @foreach($posts as $i => $p)
                 <tr>
                    <td>{{ $i + $posts->firstItem() }}</td>
                    <td>{{ $p->title }}</td>
                    <td>{{ $p->excerpt }}</td>
                  
                    <td>
                        <img src="{{ url('storage/'.$p->image) }}" alt="" style="width: 50px; height: 50px; object-fit: contain">
                    </td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{{ route('admin.post.edit', [$post_type->slug, $p->slug]) }}">Edit</a>
                                {{ Form::open(['url' => route('admin.post.destroy', [$post_type->slug, $p->slug]), 'method' => 'delete']) }}
                                <button class="dropdown-item">Delete</button>
                                {{ Form::close() }}
                            </div>
                        </div>                 
                    </td>
                </tr>
                @endforeach
                </tbody>
                </table>
             {{ $posts->links("pagination::bootstrap-4") }}
                        </div>
                    </div>
                    </div>
                </div>
@endsection