routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\RegisterController;
  
Route::get('admission', [RegistrationController::class, 'index']);
Route::post('admission', [RegistrationController::class, 'store']);

Route::get('storage', function () {
    return \Artisan::call('storage:link');
});

Route::group(['namespace' => 'App\Http\Controllers'], function ()
 {
    Route::group(['prefix'=>'admin-control', 'as'=>'admin.'] , function(){

        Route::get('/login','LoginController@index')->name('login');
        Route::post('/login','LoginController@login')->name('login');

      Route::group(['middleware' => 'admin'], function(){
          Route::get('/logout','LoginController@logout')->name('logout');
          Route::get('/','DashboardController@dashboard')->name('dashboard');
          Route::get('editprofile','EditprofileController@index')->name('editprofile');
          Route::get('changepassword','ChangepasswordController@index')->name('changepassword');
          Route::get('sitesetting','SiteController@index')->name('sitesetting');
          
          Route::post('sitesetting','SiteController@store')->name('site.store');
          Route::get('menu_item/delete', 'MenuItemController@destroy')->name('menu_item.destroy');

          // Route::delete('media/delete/{media}', 'MediaController@destroy')->name('media.destroy');
          // Route::get('media/update', 'MediaController@destroy')->name('media.update');
      
          // Route::get('menu', 'SelectmenuController@create')->name('menu.create');
          // Route::get('menu', 'SelectmenuController@index')->name('menu.index');
          // Route::get('menuit', 'MenuController@create')->name('menuit.create');
          // Route::get('menuit', 'MenuController@index')->name('menuit.index');

          Route::resources([
            'menu'      => 'MenuController',
            'menu-item' => 'MenuItemController',
            'media'     =>  'MediaController',
          ]);

          Route::post('menu-item/sort', 'MenuItemController@updateSort')->name('menu-item.update.sort');
        
          Route::get('category/{post_type:slug}', 'CategoryController@index')->name('category.index');
          Route::get('category/{post_type:slug}/create', 'CategoryController@create')->name('category.create');
          Route::get('category/{post_type:slug}/edit/{category:slug}', 'CategoryController@edit')->name('category.edit');
          Route::put('category/{post_type:slug}/update/{category:slug}', 'CategoryController@update')->name('category.update');
          Route::delete('category/{post_type:slug}/delete/{category:slug}', 'CategoryController@destroy')->name('category.destroy');
          Route::post('category/{post_type:slug}/store', 'CategoryController@store')->name('category.store');


          Route::get('{post_type:slug}', 'PostController@index')->name('post.index');
          Route::get('{post_type:slug}/create', 'PostController@create')->name('post.create');
          Route::get('{post_type:slug}/edit/{post:slug}', 'PostController@edit')->name('post.edit');
          Route::put('{post_type:slug}/update/{post:slug}', 'PostController@update')->name('post.update');
          Route::delete('{post_type:slug}/delete/{post:slug}', 'PostController@destroy')->name('post.destroy');
          Route::post('{post_type:slug}/store', 'PostController@store')->name('post.store');
      });
  });

  # Web Routes
  Route::group(['namespace' => 'Web'], function () {
    Route::get('/', 'HomeController@index')->name('Home');
    Route::post('/contact', 'ContactUsController@sendEnquiry')->name('contact.send');
    Route::post('/admission', 'RegistrationController@sendEnquiry')->name('admission.send');
    
    Route::get('/{post:slug}', 'PostController@show')->name('post.show');
  });

  
    
});

resources/views/backend/pages/changepassword.blade.php
    @extends('backend.layouts.inner')
    @section('content')
        <div class="mainDiv" >
        <div class="cardStyle">
            <form action="" method="post" name="signupForm" id="signupForm">
            
            <!-- <img src="{{url('admin\assets\images\portfolio\item-3.jpg')}}" id="signupLogo"/> -->
            
            <h2 class="formTitle align-center">
                Login to your account
            </h2>

            <div class="inputDiv">

            <label class="inputLabel" for="password">Current Password</label>
            <input type="password" id="password" name="password" required>
            </div>
            
            <div class="inputDiv">

            <label class="inputLabel" for="password">New Password</label>
            <input type="password" id="password" name="password" required>
            </div>
            
            <div class="inputDiv">
            <label class="inputLabel" for="confirmPassword">Confirm Password</label>
            <input type="password" id="confirmPassword" name="confirmPassword">
            </div>

            <div class="buttonWrapper">
            <button type="submit" id="submitButton" onclick="validateSignupForm()" class="submitButton pure-button pure-button-primary">
                <span>Continue</span>
                <!-- <span id="loader"></span> -->
            </button>
            </div>
            
        </form>
        </div>
        </div>
@endsection

resources/views/backend/pages/editprofile.blade.php
@extends('backend.layouts.inner')
@section('content')
<div class="container rounded bg-white align-items-center mb-5">
    <!-- <div class="row"> -->
        <div class="col-lg-3"></div>
        <div class="col-lg-12 border-right ">
            
            <div class="d-flex flex-column align-items-center text-center p-3 "><img class="rounded-circle mt-1" src="{{url('assets\images\menu\banner-1.jpg')}}"><span class="font-weight-bold">Amelly</span><span class="text-black-50">amelly12@bbb.com</span><span> </span></div>
        
    
            <div class="p-3 ">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Settings</h4>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><label class="labels">Name</label><input type="text" class="form-control" placeholder="first name" value=""></div>
                    <div class="col-md-6"><label class="labels">Surname</label><input type="text" class="form-control" value="" placeholder="surname"></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">PhoneNumber</label><input type="text" class="form-control" placeholder="enter phone number" value=""></div>
                    <div class="col-md-12"><label class="labels">BIO</label><input type="text" class="form-control" placeholder="enter Bio" value=""></div>
                </div>
                
                <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="button">Save Profile</button></div>
            </div>
        
</div>
    </div>
</div>
</div>
</div>
@endsection

resources/views/backend/pages/login.blade.php
@extends('backend.layouts.app')

@section('main_content')
    <div id="layoutAuthentication"style="
    height: 100vh;
    display: flex;
    flex-direction: column;
    justify-content: space-between;">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                <div class="card-body">
                                    @if($errors->any())
                                        <div class="alert alert-danger">
                                            {{ $errors->first() }}
                                        </div>
                                    @endif

                                    {{ Form::open(['url' => route('admin.login'), 'method' => 'post']) }}
                                        <div class="form-group">
                                            <label class="small mb-1" for="inputEmailAddress">Email</label>
                                            <input class="form-control py-4" id="inputEmailAddress" type="email" name="email" placeholder="Enter email address" />
                                        </div>
                                        <div class="form-group">
                                            <label class="small mb-1" for="inputPassword">Password</label>
                                            <input class="form-control py-4" id="inputPassword" type="password" name="password" placeholder="Enter password" />
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox">
                                                <input class="custom-control-input" id="rememberPasswordCheck" name="remember" type="checkbox" />
                                                <label class="custom-control-label" for="rememberPasswordCheck">Remember password</label>
                                            </div>
                                        </div>
                                        <div class="form-group d-flex text-right mt-4 mb-0">
                                            <button class="btn btn-primary " >Login</button>
                                        </div>
                                    {{ Form::close() }}
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2020</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
@endsection

resources/views/backend/pages/sitesetting.blade.php
 @extends('backend.layouts.inner')

@section('site_title', 'Site Setting | ')

@section('content')
    <div class="container-fluid py-4">
        {{ Form::open(['url' => route('admin.site.store'), 'files' => true]) }}
       <div>
                <div class="mb-3">
                {{ Form::label('title', 'Site Title') }}
                {{ Form::text('title', null, ['class' => 'form-control title', 'placeholder' => 'Enter Title', 'data-target' => '#slug']) }}
            </div>
            <div class="mb-3">
                {{ Form::label('tagline') }}
                {{ Form::text('tagline', null, ['class' => 'form-control', 'placeholder' => 'Enter tagline']) }}
            </div>
            <div class="mb-3">
                {{ Form::label('logo') }}
                {{ Form::file('logo', ['class' => 'form-control'])}}
            </div>
            <div class="mb-3">
                {{ Form::label('footer_logo') }}
                {{ Form::file('footer_logo', ['class' => 'form-control'] )}}
            </div>
        </div>
            <div class=" mb-3 py-4">
                {{ Form::label('favicon') }}
                {{ Form::file('favicon', ['class' => 'form-control']) }}
            </div>
            <div class=" mb-3  py-4">
                {{ Form::label('footer_script') }}
                {{ Form::textarea('footer_script', null, ['class' => 'form-control', 'placeholder' => 'Enter Description']) }}
            </div>
            <div class="mb-3  py-4">
                {{ Form::label('email') }}
                {{ Form::text('email', null, ['class' => 'form-control', 'placeholder' => 'Enter email']) }}
            </div>
            <div class="mb-3  py-4">
                {{ Form::label('phone') }}
                {{ Form::text('phone', null, ['class' => 'form-control', 'placeholder' => 'Enter phone no.']) }}
            </div>
            <div class="mb-3  py-4">
                {{ Form::label('address') }}
                {{ Form::textarea('address', null, ['class' => 'form-control', 'placeholder' => 'Enter your address']) }}
            </div>
            <div class="text-center">
            <button type="submit" class="btn btn-primary btn-lg">Save</button>
            </div>
        </div> 
        {{ Form::close() }}   
    </div>
@endsection